---
title: "Importances Misty for SCNA"
output: html_notebook
---



```{r}
library(mistyR)
library(tidyverse)
library(stringr)

```

Load in data, let's only load juxtaview 30 from 2 cohorts

```{r}
csv_dir <- "./../../output/"

# Recursively list all .csv files in the directory and its subdirectories
data <- list.files(path = csv_dir, recursive = TRUE, pattern = "\\juxta.30.txt$")

```
Read in and format all data
```{r}
all = list()

for (i in data){
  all[[i]] <- read_csv(paste0(csv_dir,i))
}

tab = data.frame(target = character(),
                 imp = double(),
                 label1 = character(),
                 sample = character())

names = unique(sub("/.*", "", data))
subnames = unique(sub("^.*/", "", data))
for (i in names){
  for (x in subnames){
    dat = all[[paste(i, x, sep = "/")]]
    dat$label1 = rep(str_extract(x, "ct\\d+"), times= length(nrow(dat)))
    dat$sample = rep(i, times= length(nrow(dat)))
    tab = rbind(tab, dat)
  }
}

# create labels for interactinos
tab$interaction =  paste(tab$target, tab$label1, sep = "_")
tab = tab %>% select(-target, -label1)
```
Now get it in heatmap format

```{r}
try = as.data.frame(spread(tab, key = interaction, value = imp))

# just form hierarchically clustered heatmap for all samples to get a feeling for the interactions

library(ggplot2)
library(pheatmap)

rownames(try) = try$sample
pheatmap(try[,-1], treeheight_row = 50, treeheight_col = 1)
```


