---
title: "Victor_GSK_data"
author: "Chiara Schiller"
date: "2023-06-09"
output: html_document
---
Run MISTy for 3 samples from Victor.

Load packages
```{r}
library(mistyR)
library(tidyverse)
library(magrittr)
library(future)
library(ggvoronoi)
library(cowplot)
library(pheatmap)
library(grid)
```

Load in one sample to explore data
```{r}
data = read_csv("./../../../../data/Victor_protein_GSK/rack1_hi_backsub--unmicst_cell.h5ad.csv")
head(data)
```


Run MIsty. Script adapted from: https://github.com/saezlab/misty_pipelines/blob/master/imc/imc_large_pipeline.R
```{r}

plan(multiprocess, workers = 4)

paths <- list.files("./../../../../data/Victor_protein_GSK/", full.names = TRUE)

# define view threshold
neighbor.thr <- 200
l <- 400

paths %>% walk(function(path){

  data <- read_csv(path)
  index = grep("X_centroid", colnames(data)) -1
  
  # exclude DAPI from analysis
  expr <- data[ , 3:index]
  # get geometry
  pos <- data %>% select(X_centroid, Y_centroid)
  
  # filter nans
  pos.complete <- which(complete.cases(pos))
  
  expr <- expr %>% slice(pos.complete)
  pos <- pos %>% slice(pos.complete)
  
  #misty
  views <- create_initial_view(expr) %>%
    add_juxtaview(pos, neighbor.thr, cached = FALSE) %>%
    add_paraview(pos, l, zoi = neighbor.thr, cached = FALSE) %>%
    add_paraview(pos, l = 2000, zoi = neighbor.thr, cached = FALSE)
  
  run_misty(views, results.folder = paste0("./../../output/Victor_GSK_protein/",basename(path)), cached = FALSE)
}) -> result.folders



```
```{r}
misty.results <- collect_results(result.folders)
summary(misty.results)
```

## Visualization

```{r}
#create standard comparison matrix
csv_dir <- "./../../output/Victor_GSK_protein/"

# Recursively list all .csv files in the directory and its subdirectories

#data <- list.files(path = csv_dir, recursive = TRUE, pattern = "\\juxta.30.txt$")

data <- list.files(path = csv_dir, recursive = TRUE, pattern = "\\intra.txt$")
basename(data)
all = list()


for (i in 1:length(data)){
  all[[i]] <- read_csv(paste0(csv_dir,data[i]))
  names(all)[i] = basename(data)[i]
  all[[i]]$label1 = rep(basename(data)[i], nrow(all[[i]]))
  all[[i]]$label1 = sub("importances_", "", all[[i]]$label1 )
  all[[i]]$label1 = sub("_intra.txt", "", all[[i]]$label1 )
  all[[i]]$image_id = rep(sub("/.*$", "", data[i]), nrow(all[[i]]))
}

dat_all = do.call("rbind", all)

```

##Visualization of target-importance relationships

```{r}
# data wrangling
#write_csv(dat_all, "./../../output/Victor_GSK_protein/table_files_para.400.csv")
see = spread(dat_all, value = "imp", key = "label1", drop = FALSE)

# save data for Victor
colnames(dat_all) = c("target", "importance", "predictor", "image_id")

write_csv(dat_all, "./../../output/Victor_GSK_protein/20230613table_intra_Victor_GSK.csv")


unique(see$image_id)
rack1_hi_backsub = see %>% filter(image_id == "rack2_hi_backsub--unmicst_cell.h5ad.csv") %>% 
  select(- ErbB_2) %>% 
  select(-image_id) %>% as.data.frame() 

rownames(rack1_hi_backsub) = rack1_hi_backsub$target
rack1_hi_backsub = rack1_hi_backsub[ ,-1]
rack1_hi_backsub = rack1_hi_backsub[ -grep("ErbB_2", rownames(rack1_hi_backsub)), ]

```
add labels
```{r}

#pdf("./../../output/Victor_GSK_protein/plots/intra_rack2_hi_backsub.pdf", width = 6.5, height = 5.5)

setHook("grid.newpage", function() pushViewport(viewport(x=1,y=1,width=0.9, height=0.9, name="vp", just=c("right","top"))), action="prepend")
pheatmap(rack1_hi_backsub, treeheight_row = 0, treeheight_col = 0, 
         main = "intra.view, rack2_hi_backsub",
         cluster_rows = F,
         cluster_cols =  F)
setHook("grid.newpage", NULL, "replace")
grid.text("Predictor", y=-0.01, x = 0.32, gp=gpar(fontsize=14))
grid.text("Target", x=-0.07, y = 0.6,rot=90, gp=gpar(fontsize=14))
#dev.off()
```


```{r}
sessionInfo()
```















